### ISSUE TITLE
Profile picture is not displayed 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/eks-deployment#67]
STR:
1. Login to mozillians staging
2. Navigate to Settings page
3. Add a profile photo, the click "Update Information" button

Expected:
The profile picture is correctly displayed

Actual:
The profile picture is not correctly displayed

![upload profile picture](https://user-images.githubusercontent.com/5293100/46408908-60b0a080-c71c-11e8-9758-ea9c0b658941.png)

**Comment by danielhartnell** [comment]
The media path is configured to match the other staging website. This attempts to request assets from https://cdn-staging.mozillians.org/media/ which does not use Kubernetes as an origin today. Profile images are successfully uploaded but they reside on the pod in Kubernetes so the asset fails to load after the upload.

Once we have shared storage (S3, EBS, etc.) which is shared by all pods, we can probably go ahead and copy the data from the other AWS account and then update the media URL to point to Kubernetes. We can add a new CDN in the account to front that as well but it's not required right now.

**Comment by danielhartnell** [comment]
https://github.com/kubernetes/kubernetes/issues/2630

I wanted to add EBS-backed shared storage for each pod as a backup just in case we can't add S3 storage soon. It turns out, there are some issues doing this when you are not running the `ENTRYPOINT` / `CMD` as root. In the case of Mozillians, we are using an webdev user. Kubernetes volumes will mount as root and this user won't have access to write. There's a workaround to add an init container which will chown the mount with the desired uid / gid but this could be problematic if that ID changes. I assume this is likely if the pod jumps to a new node with a new shared kernel.

There's another workaround provided in the issue above which suggests keeping the `USER` as root in the Dockerfile and then running a script for your entrypoint as a new user.

**Comment by danielhartnell** [comment]
This has been addressed by using an S3 bucket for the media storage backend.
